name: flashtalk

services:      

  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - flashtalk_net1
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - ./certs:/etc/prometheus/certs:ro  # монтируем папку с сертификатами
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
 
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - flashtalk_net1
  #   environment:
  #     - GF_LOG_LEVEL=error
  #     - GF_LOG_LEVEL_PLUGINS_UPDATE_CHECKER=error
  #     - GF_LOG_LEVEL_CLEANUP=error
  #     - GF_LOG_LEVEL_INFRA_USAGESTATS=error
  #   volumes:
  #     - grafana_data:/var/lib/grafana  # для сохранения данных между перезапусками
  #   restart: unless-stopped

  flashtalk_db: 
    image: postgres 
    ports:
      - "5432:5432"
    networks:
        - flashtalk_net1
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: flashtalk_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_log:/var/log/postgresql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 5


  flashtalk_api_1:
    image: gatewayapi
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile
    #command: ["migrate"] # flag to start the migration process
    ports:
      - "4442:442"
    networks:
      - flashtalk_net1
    environment:
      - ConnectionStrings__FlashTalkConnectionString=${FLASHTALK_DB_CONNECTION_STRING} # connection string from .env or secrets
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:442
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - data-protection-keys:/app/DataProtection-Keys
      - ./certs:/https:ro
    depends_on:
      flashtalk_db:
        condition: service_healthy

  flashtalk_api_2:
    image: gatewayapi
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile
    #command: ["migrate"] # flag to start the migration process
    ports:
      - "4443:443"
    networks:
      - flashtalk_net1
    environment:
      - ConnectionStrings__FlashTalkConnectionString=${FLASHTALK_DB_CONNECTION_STRING} # connection string from .env or secrets
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - data-protection-keys:/app/DataProtection-Keys
      - ./certs:/https:ro
    depends_on:
      flashtalk_db:
        condition: service_healthy

  flashtalk_client_web_blazor_1:
    image: client.web.blazor
    build:
      context: .
      dockerfile: Client.Web.Blazor/Dockerfile
    ports:
      - "4445:445"
    networks:
      - flashtalk_net1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:445
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - data-protection-keys:/app/DataProtection-Keys
      - ./certs:/https:ro
    depends_on:
      - flashtalk_api_1
      - flashtalk_api_2

  flashtalk_client_web_blazor_2:
    image: client.web.blazor
    build:
      context: .
      dockerfile: Client.Web.Blazor/Dockerfile
    ports:
      - "4446:446"
    networks:
      - flashtalk_net1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:446
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - data-protection-keys:/app/DataProtection-Keys
      - ./certs:/https:ro
    depends_on:
      - flashtalk_api_1
      - flashtalk_api_2

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "444:444"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/https:ro
    networks:
      - flashtalk_net1
    depends_on:
      - flashtalk_client_web_blazor_1
      - flashtalk_client_web_blazor_2

networks:
  flashtalk_net1:
    driver: bridge

volumes:
  grafana_data:
  postgres_data:
  data-protection-keys: